//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class amphur
    {
        public int AMPHUR_ID { get; set; }
        public string AMPHUR_CODE { get; set; }
        public string AMPHUR_NAME { get; set; }
        public string AMPHUR_NAME_ENG { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<int> GEO_ID { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
    }
}
