//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITAL
    {
        public int ID { get; set; }
        public string MainHospitalCode { get; set; }
        public string OldCode { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string HospitalType2Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
    }
}
