//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_th
    {
        public string id1 { get; set; }
        public string id2 { get; set; }
        public string pname { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string id3 { get; set; }
    }
}
