//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string nick_name { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string education { get; set; }
        public string career { get; set; }
    }
}
