//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAMBON
    {
        public int ID { get; set; }
        public string AD_LEVEL { get; set; }
        public string TA_ID { get; set; }
        public string TAMBON_T { get; set; }
        public string TAMBON_E { get; set; }
        public string AM_ID { get; set; }
        public string AMPHOE_T { get; set; }
        public string AMPHOE_E { get; set; }
        public string CH_ID { get; set; }
        public string CHANGWAT_T { get; set; }
        public string CHANGWAT_E { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
    }
}
