//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thailandEntities1 : DbContext
    {
        public thailandEntities1()
            : base("name=thailandEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amphur> amphurs { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<geography> geographies { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<person_th> person_th { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<village2010> village2010 { get; set; }
        public virtual DbSet<SCHOOL> SCHOOLs { get; set; }
        public virtual DbSet<TAMBON> TAMBONs { get; set; }
        public virtual DbSet<HOSPITAL> HOSPITALs { get; set; }
    }
}
