//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class village2010
    {
        public int id { get; set; }
        public string VILL_NO { get; set; }
        public string VILL_CODE { get; set; }
        public string TAM_CODE { get; set; }
        public string AMP_CODE { get; set; }
        public string PROV_CODE { get; set; }
        public string VILL_T { get; set; }
        public string TAM_T { get; set; }
        public string AMP_T { get; set; }
        public string PROV_T { get; set; }
    }
}
